name: deployment
on: [push]
jobs:

  build:
    name: SSH request
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /home/alex/skripte/deployment.sh 2>&1 | tee "home/alex/logs/deployment/deploy_log_$(date +"%Y-%m-%d_%T").txt"
